/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.13/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "hexArchWebApplication"
val version: String by settings
val group: String by settings

gradle.beforeProject {
    this.group = group
    this.version = version
}

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}


rootProject.name = "hexArchWebApplication"
include( "boot-configuration", "web-adapter", "persist-adapter", "port-web", "port-persist", "application", "domain-logic")

dependencyResolutionManagement {
    repositories {
        mavenLocal()
        mavenCentral()
    }
}

